### ISSUE TITLE
How real videos are obtained about DF-W ?

### ISSUE THREAD

**Issue by fhlt** [jmpu/webconf21-deepfakes-in-the-wild#1]

**Comment by jmpu** [comment]
The negative-class videos (real videos) for evaluating models on DF-W were simply sampled from real videos of the DF-R dataset (which are real videos from 6 research community datasets we studied). The slight difference is that we didn’t use all the real videos of DF-R. If you check out table 3, we proportionally sampled 1,864 real videos (from each subset of DF-R) to evaluate DF-W.
